### ISSUE TITLE
Native tests not working

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-kerberos#41]
Ecosystem CI says that the native tests are not working and I was able to reproduce it locally:
```
[ERROR] Failures: 
[ERROR]   KerberosResourceIT>KerberosResourceTestCase.testSpnegoSuccess:55 1 expectation failed.
Response body doesn't match expectation.
Expected: is "jduke jduke@QUARKUS.IO QUARKUS.IO"
  Actual: 
```

/cc @cescoffier @sberyozkin

**Comment by sberyozkin** [comment]
Stuart looked briefly into adding a native support but we haven't really expected the tests pass in native mode as there as no immediate demand in it; I'll have a look but a bit later

**Comment by aanavaneeth** [comment]
We use MIT Kerberos and we use native Kerberos with Java. Can we look into this? A lot of enterprise users will benefit out of this.

**Comment by gastaldi** [comment]
I fixed this in https://github.com/quarkiverse/quarkus-kerberos/commit/608158326f650e5accfd0ecb6820ca784f2ebe37
