### ISSUE TITLE
Kerberos not working with quarkus

### ISSUE THREAD

**Issue by AnkitSaxena03** [quarkiverse/quarkus-kerberos#51]
HI Team,

I am trying to implement kerberos auth with quarkus.

Below are the steps which I have done.

Added kerberos dependency in pom.

Added below in properties file
quarkus.kerberos.enabled=true
#quarkus.kerberos.login-context-name=
quarkus.kerberos.keytab-path=/temp/fidtestpprd.keytab
quarkus.kerberos.use-spnego-oid=false
quarkus.kerberos.service-principal-name=fidtestpprd
quarkus.kerberos.service-principal-realm=Example.com
quarkus.kerberos.service-principal-password=pwd

Added jaas config and krb5 in jvm args in docker file.
java $JAVA_OPTS -Djava.security.auth.login.config=/temp/kerberos_jaas.conf -Djava.security.krb5.conf=/temp/krb5.conf

I am deploying on OCP. No logs come up  on OCP console related to krb5 and I am getting unauthorized exception while calling the app.

Response:

HTTP/1.1 401 Unauthorized
www-authenticate: Negotiate
content-length: 0

**Comment by AnkitSaxena03** [comment]
@sberyozkin :  After enabling debug also, nothing comes up on OCP pod logs

**Comment by sberyozkin** [comment]
Then please confirm it works for you with OCP first

**Comment by sberyozkin** [comment]
@AnkitSaxena03 I've added a note about debugging:

https://github.com/quarkiverse/quarkus-kerberos/commit/0cb02fb6954d095877eb90b7f0eab1051aa5e074

If that does not yield anything then I'd like to see a simple reproducer, where you use `curl` as doc-ed in `Getting Started`
